/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remainder.ui;

import remainder.model.Remainder;
import remainder.model.Status;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajya Laxmi Maharjan &lt;
 */
public class CreateRemainderGUI extends javax.swing.JFrame {
    public static ArrayList<Remainder> remainders = new ArrayList();

    private SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

    public static StringBuilder remainderNameList = new StringBuilder();

    /** Creates new form CreateRemainderGUI */
    public CreateRemainderGUI() {
        initComponents();
        init();

    }

    public void init() {

        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        int year = cal.get(Calendar.YEAR);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        yearTf.setText("" + year);
        yearTf.setEditable(false);
        System.out.println("month : " + month);
        mthTf.setText("" + (month + 1));
        mthTf.setEditable(false);
        dateTf.setText("" + day);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        remindMePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        mthTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dateTf = new javax.swing.JTextField();
        yearTf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        hourTf = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        minuteTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messagetf = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listOfReminderLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        remindBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 233, 233));

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));

        jPanel2.setBackground(new java.awt.Color(233, 233, 233));

        remindMePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel14.setText("Year");

        mthTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        mthTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        mthTf.setDisabledTextColor(new java.awt.Color(236, 222, 225));
        mthTf.setSelectionColor(new java.awt.Color(236, 233, 225));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel15.setText("Month");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel16.setText("Date");

        dateTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dateTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        dateTf.setDisabledTextColor(new java.awt.Color(236, 222, 225));
        dateTf.setSelectionColor(new java.awt.Color(236, 233, 225));

        yearTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        yearTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        yearTf.setDisabledTextColor(new java.awt.Color(236, 222, 225));
        yearTf.setSelectionColor(new java.awt.Color(236, 233, 225));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel17.setText("Hour");

        hourTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        hourTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        hourTf.setDisabledTextColor(new java.awt.Color(236, 222, 225));
        hourTf.setSelectionColor(new java.awt.Color(236, 233, 225));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel18.setText("Minute");

        minuteTf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        minuteTf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        minuteTf.setDisabledTextColor(new java.awt.Color(236, 222, 225));
        minuteTf.setSelectionColor(new java.awt.Color(236, 233, 225));

        javax.swing.GroupLayout remindMePanelLayout = new javax.swing.GroupLayout(remindMePanel);
        remindMePanel.setLayout(remindMePanelLayout);
        remindMePanelLayout.setHorizontalGroup(
            remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindMePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remindMePanelLayout.createSequentialGroup()
                        .addComponent(hourTf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(remindMePanelLayout.createSequentialGroup()
                        .addComponent(yearTf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remindMePanelLayout.createSequentialGroup()
                        .addComponent(mthTf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minuteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        remindMePanelLayout.setVerticalGroup(
            remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindMePanelLayout.createSequentialGroup()
                .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(remindMePanelLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(yearTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remindMePanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(mthTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(dateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(remindMePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hourTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(minuteTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setText("Message");

        messagetf.setColumns(20);
        messagetf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        messagetf.setRows(5);
        messagetf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        messagetf.setDoubleBuffered(true);
        jScrollPane2.setViewportView(messagetf);

        jPanel3.setBackground(new java.awt.Color(10, 118, 155));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Remainder");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        listOfReminderLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Remainder List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(remindMePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(listOfReminderLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(remindMePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listOfReminderLabel)
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 351, Short.MAX_VALUE)))
        );

        remindBttn.setBackground(new java.awt.Color(10, 118, 155));
        remindBttn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        remindBttn.setForeground(new java.awt.Color(255, 255, 255));
        remindBttn.setText("Remind");
        remindBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 233, 225)));
        remindBttn.setFocusable(false);
        remindBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remindBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(remindBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(remindBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String changeDate(String d) {
        String date = null;

        if (d.equals("")) {
            System.out.println("null");
            date = "00";

        } else {
            if (d.length() == 2) {
                date = d;
            } else if (d.length() == 1) {

                date = "0" + d;
                System.out.println("yeta pugyo " + date);
            }

        }
        return (date);
    }
    private void remindBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remindBttnActionPerformed
        //fields verification
        verify();
        //date fields converted to calendar
        Calendar cal = dateModified();

        final Remainder remainder = new Remainder(messagetf.getText(), new Date(), Status.REMIND_ON, cal.getTime());
        remainders.add(remainder);
        //listing names of remainder
        remainderNameList.append(remainder.getMessage() + " , \n");
        listOfReminderLabel.setText(remainderNameList.toString());
        //finished creating remainder
        JOptionPane.showMessageDialog(null, "Successfully created remainder");
        clear();
//New thread for checking the remainder date and current date
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
                try {
                    new RemindNotification(remainder);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }

        };
        runnable.run();
    }//GEN-LAST:event_remindBttnActionPerformed

    public Calendar dateModified() {
        int year, month, date;
        String hour, minute;

        if (dateTf.getText().equals("")) {
            System.out.println("null");
            date = 0;

        } else {
            date = Integer.parseInt(dateTf.getText());
        }
        hour = changeDate(hourTf.getText());
        minute = changeDate(minuteTf.getText());

        Calendar cal = Calendar.getInstance();

        // print current time
        // set the year,month and day to something else
        cal.set(Integer.parseInt(yearTf.getText()), Integer.parseInt(mthTf.getText()) - 1,
                  Integer.parseInt(dateTf.getText()), Integer.parseInt(hourTf.getText()), Integer.parseInt(
                            minuteTf.getText()), 0);
        return cal;
    }

    public void verify() {
        if (dateTf.getText().equals("") || hourTf.getText().equals("") || minuteTf.getText().equals("")) {
            System.out.println("date : " + dateTf.getText());
            System.out.println("hour : " + hourTf.getText());
            System.out.println("minute : " + minuteTf.getText());
            JOptionPane.showMessageDialog(null, "Emptyy Fields");
            return;
        }
        if (messagetf.getText().equals("")) {
            messagetf.setText("Alarm " + (remainders.size() + 1));
        }

    }

    public void clear() {
        messagetf.setText("");

        hourTf.setText("");
        minuteTf.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRemainderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                      null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRemainderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                      null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRemainderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                      null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRemainderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                      null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRemainderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTf;
    private javax.swing.JTextField hourTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listOfReminderLabel;
    private javax.swing.JTextArea messagetf;
    private javax.swing.JTextField minuteTf;
    private javax.swing.JTextField mthTf;
    private javax.swing.JButton remindBttn;
    private javax.swing.JPanel remindMePanel;
    private javax.swing.JTextField yearTf;
    // End of variables declaration//GEN-END:variables
}
